import { strict as assert } from 'node:assert';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, readdirSync, rmSync, realpathSync, cpSync, symlinkSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { spawnSync } from 'node:child_process';
import { randomUUID } from 'node:crypto';
import { lessonState } from '../lib/lesson-state.mjs';
const root=realpathSync(mkdtempSync(join(tmpdir(),'loop-lessons-real-verifier-fixture-')));
const vr=resolve(import.meta.dirname,'../bin/verdict-run.sh'),lessons=resolve(import.meta.dirname,'../bin/lessons.mjs');
const env={PATH:process.env.PATH,LOOP_DIR:'.loop',LOOP_RUN_ID:randomUUID()};
const run=(bin,args,extra={})=>spawnSync(bin,args,{cwd:root,env:{...env,...extra},encoding:'utf8'});
try {
  assert.equal(run('git',['init','-q']).status,0);
  writeFileSync(join(root,'.gitignore'),'.loop/\n');
  writeFileSync(join(root,'implementation.txt'),'broken');
  writeFileSync(join(root,'verify.sh'),'#!/bin/sh\n[ "$(cat implementation.txt)" = fixed ] && exit 0\necho "FAIL: implementation is broken"\nexit 1\n');
  run('git',['add','.']);assert.equal(run('git',['-c','user.name=Fixture','-c','user.email=fixture@example.invalid','commit','-qm','fixture']).status,0);
  mkdirSync(join(root,'.loop'));
  const first=run('bash',[vr,'--log','.loop/first.log','--','sh','verify.sh']);
  assert.equal(first.status,1,first.stderr);writeFileSync(join(root,'.loop/first-verdict.txt'),first.stdout);
  const failState=JSON.parse(readFileSync(join(root,'.loop/verdict-state.json')));
  writeFileSync(join(root,'implementation.txt'),'fixed');
  const second=run('bash',[vr,'--log','.loop/second.log','--','sh','verify.sh']);assert.equal(second.status,0,second.stderr);
  const passState=JSON.parse(readFileSync(join(root,'.loop/verdict-state.json')));
  const args=['record','--verified','--signature-file','.loop/first-verdict.txt','--receipt',`.loop/evidence/${passState.receipt_id}.json`,'--failure-receipt',`.loop/evidence/${failState.receipt_id}.json`,'--fix','change implementation value to fixed'];
  const result=run(process.execPath,[lessons,...args]);assert.equal(result.status,0,result.stderr);
  const files=readdirSync(join(root,'.loop/lessons')).filter(f=>f.endsWith('.json'));assert.equal(files.length,1);
  const lesson=JSON.parse(readFileSync(join(root,'.loop/lessons',files[0])));
  assert.equal(lesson.verification.receipts[0].id,passState.receipt_id);
  assert.notEqual(lesson.verification.receipts[0].fix_target_before,lesson.verification.receipts[0].fix_target_after);
  assert.equal(lessonState(lesson,{root}).verified,true,'actual producer seal and receipts are readable');
  const feature=join(root,'.loop/linked-feature');
  assert.equal(run('git',['-c','core.hooksPath=/dev/null','worktree','add','--detach',feature,'HEAD']).status,0);
  const featureEnv={...env,LOOP_RUN_ID:randomUUID()};
  const atFeature=(bin,args)=>spawnSync(bin,args,{cwd:feature,env:featureEnv,encoding:'utf8'});
  const f=atFeature('bash',[vr,'--log','.loop/fail.log','--','sh','verify.sh']);assert.equal(f.status,1);
  writeFileSync(join(feature,'.loop/failure.txt'),f.stdout);
  const fs=JSON.parse(readFileSync(join(feature,'.loop/verdict-state.json')));
  writeFileSync(join(feature,'implementation.txt'),'fixed');
  const p=atFeature('bash',[vr,'--log','.loop/pass.log','--','sh','verify.sh']);assert.equal(p.status,0);
  const ps=JSON.parse(readFileSync(join(feature,'.loop/verdict-state.json')));
  const recorded=atFeature(process.execPath,[lessons,'record','--verified','--signature-file','.loop/failure.txt',
    '--receipt',`.loop/evidence/${ps.receipt_id}.json`,'--failure-receipt',`.loop/evidence/${fs.receipt_id}.json`,'--fix','actual linked-worktree fix']);
  assert.equal(recorded.status,0,recorded.stderr);
  const featureLesson=JSON.parse(readFileSync(join(feature,'.loop/lessons',files[0])));
  assert.equal(lessonState(featureLesson,{root:feature}).verified,true,'genuine linked-worktree learning is valid in its original execution root');
  const historyDir=join(root,'.git/loop/lesson-history');
  const ioFailure=`import fs from 'node:fs'; import {syncBuiltinESMExports} from 'node:module';
    const write=fs.writeFileSync; fs.writeFileSync=(file,data,...rest)=>{
      if(String(file).includes('/loop/lesson-history/')) { write(file,'{',...rest); throw Object.assign(new Error('injected partial write'),{code:'ENOSPC'}); }
      return write(file,data,...rest);
    }; syncBuiltinESMExports();`;
  const interrupted=atFeature(process.execPath,['--import','data:text/javascript;base64,'+Buffer.from(ioFailure).toString('base64'),lessons,'preserve','--id',featureLesson.id]);
  assert.equal(interrupted.status,2); assert.match(interrupted.stderr,/injected partial write/);
  assert.deepEqual(readdirSync(historyDir),[],'failed writes must leave no published or temporary history');
  const preserved=atFeature(process.execPath,[lessons,'preserve','--id',featureLesson.id]);
  assert.equal(preserved.status,0,preserved.stderr);
  const archive=JSON.parse(preserved.stdout);
  assert.equal(archive.current_verified,false);
  assert.equal(archive.lesson.verified,false);
  assert.equal(archive.evidence.length,3,'keep the original FAIL, PASS and producer seal');
  assert.equal(lessonState(archive.lesson,{root}).verified,false);
  const duplicate=atFeature(process.execPath,[lessons,'preserve','--id',featureLesson.id]);
  assert.equal(duplicate.status,0,duplicate.stderr); assert.equal(JSON.parse(duplicate.stdout).id,archive.id);
  assert.equal(readdirSync(historyDir).length,1,'retries must not multiply history');
  assert.equal(spawnSync(process.execPath,[lessons,'preserve','--id',featureLesson.id],{cwd:feature,env:{...featureEnv,LOOP_LEARNING_OFF:'1'}}).status,2);
  assert.equal(atFeature(process.execPath,[lessons,'preserve','--id','../outside']).status,2);
  const lessonFile=join(feature,'.loop/lessons',files[0]), originalLesson=readFileSync(lessonFile);
  for (const changed of [{...featureLesson,fix:'altered fix'}, {...featureLesson,invalid_at:new Date().toISOString()}, {...featureLesson,challenge:{verdict:'reject'}}, {...featureLesson,signature:[...featureLesson.signature,{injected:true}]}]) {
    writeFileSync(lessonFile,JSON.stringify(changed));
    assert.equal(atFeature(process.execPath,[lessons,'preserve','--id',featureLesson.id]).status,2,'unbacked or revoked lessons cannot gain a historical verification claim');
  }
  writeFileSync(lessonFile,originalLesson);
  const passFile=join(feature,`.loop/evidence/${ps.receipt_id}.json`), originalPass=readFileSync(passFile);
  writeFileSync(passFile,JSON.stringify({...JSON.parse(originalPass),exit:7}));
  assert.equal(atFeature(process.execPath,[lessons,'preserve','--id',featureLesson.id]).status,2);
  rmSync(passFile); symlinkSync(join(root,`.loop/evidence/${ps.receipt_id}.json`),passFile);
  assert.equal(atFeature(process.execPath,[lessons,'preserve','--id',featureLesson.id]).status,2);
  rmSync(passFile); writeFileSync(passFile,originalPass);
  featureEnv.LOOP_RUN_ID=randomUUID();
  writeFileSync(join(feature,'implementation.txt'),'broken again');
  const secondFail=atFeature('bash',[vr,'--log','.loop/second-fail.log','--','sh','verify.sh']);
  assert.equal(secondFail.status,1); writeFileSync(join(feature,'.loop/second-failure.txt'),secondFail.stdout);
  const secondFailState=JSON.parse(readFileSync(join(feature,'.loop/verdict-state.json')));
  writeFileSync(join(feature,'implementation.txt'),'fixed');
  assert.equal(atFeature('bash',[vr,'--log','.loop/second-pass.log','--','sh','verify.sh']).status,0);
  const secondPassState=JSON.parse(readFileSync(join(feature,'.loop/verdict-state.json')));
  assert.equal(atFeature(process.execPath,[lessons,'record','--verified','--signature-file','.loop/second-failure.txt',
    '--receipt',`.loop/evidence/${secondPassState.receipt_id}.json`,'--failure-receipt',`.loop/evidence/${secondFailState.receipt_id}.json`,'--fix','actual linked-worktree fix']).status,0);
  const twoRuns=JSON.parse(readFileSync(lessonFile)); assert.equal(lessonState(twoRuns,{root:feature}).receipts.length,2);
  writeFileSync(passFile,'{');
  assert.equal(lessonState(twoRuns,{root:feature}).receipts.length,1,'ordinary recall retains the independently valid run');
  assert.equal(atFeature(process.execPath,[lessons,'preserve','--id',featureLesson.id]).status,2,'preservation must reject a broken receipt even when another run remains valid');
  writeFileSync(passFile,originalPass); writeFileSync(lessonFile,originalLesson);
  const archiveFile=join(historyDir,`${archive.id}.json`), originalArchive=readFileSync(archiveFile);
  writeFileSync(archiveFile,originalArchive.toString().replace('actual linked-worktree fix','tampered archive fix'));
  assert.equal(run(process.execPath,[lessons,'history','--id',featureLesson.id]).status,2);
  assert.equal(atFeature(process.execPath,[lessons,'preserve','--id',featureLesson.id]).status,2,'preserve must not overwrite corrupted history');
  writeFileSync(archiveFile,originalArchive);
  const other=join(root,'.loop/other-repo'); mkdirSync(other);
  assert.equal(spawnSync('git',['init','-q'],{cwd:other,env}).status,0);
  const otherHistory=join(other,'.git/loop/lesson-history'); mkdirSync(otherHistory,{recursive:true});
  cpSync(archiveFile,join(otherHistory,`${archive.id}.json`));
  assert.equal(spawnSync(process.execPath,[lessons,'history','--id',featureLesson.id],{cwd:other,env}).status,2,'another repository must reject copied history');
  cpSync(join(feature,'.loop/evidence'),join(root,'.loop/evidence'),{recursive:true});
  assert.equal(lessonState(featureLesson,{root}).verified,false,'same git-common owner is not a receipt transfer approval');
  assert.equal(run('git',['-c','core.hooksPath=/dev/null','worktree','remove','--force',feature]).status,0);
  assert.equal(lessonState(featureLesson,{root}).verified,false,'cleanup cannot silently adopt foreign-worktree receipts');
  const history=run(process.execPath,[lessons,'history','--id',featureLesson.id]);
  assert.equal(history.status,0,history.stderr);
  const retained=JSON.parse(history.stdout); assert.equal(retained.length,1);
  assert.equal(run(process.execPath,[lessons,'history','--id',featureLesson.id],{LOOP_LEARNING_OFF:'1'}).status,0,'read-only history remains available when learning is frozen');
  assert.equal(retained[0].lesson.fix,'actual linked-worktree fix');
  assert.equal(retained[0].current_verified,false,'history survives cleanup without claiming current verification');
  assert.equal(lessonState(retained[0].lesson,{root}).verified,false);
  writeFileSync(join(root,'implementation.txt'),'broken again');
  const laterFail=run('bash',[vr,'--log','.loop/later-failure.log','--','sh','verify.sh']);
  assert.equal(laterFail.status,1); writeFileSync(join(root,'.loop/later-verdict.txt'),laterFail.stdout);
  const bySignature=run(process.execPath,[lessons,'history','--signature-file','.loop/later-verdict.txt']);
  assert.equal(bySignature.status,0,bySignature.stderr); assert.equal(JSON.parse(bySignature.stdout)[0].id,archive.id);
  assert.equal(JSON.parse(readFileSync(join(root,'.loop/verdict-state.json'))).verdict,'FAIL','history must not replace a failed re-verification');
  const recall=run(process.execPath,[lessons,'recall','--signature-file','.loop/later-verdict.txt']);
  assert.equal(recall.status,0); assert.doesNotMatch(recall.stdout,/actual linked-worktree fix/,'history is not injected as an authoritative local lesson');
  assert.deepEqual(JSON.parse(run(process.execPath,[lessons,'history','--id','0000000000000000']).stdout),[]);
  console.log('PASS: preserved worktree history survives cleanup, deduplicates and rejects tampering/foreign repositories without verified promotion');
  console.log('PASS: linked-worktree FAIL/fix/PASS seal is local; copied complete evidence remains unverified in canonical checkout after cleanup');
  console.log('PASS: actual verdict-run receipts + exact stdout hash + git-visible implementation fix -> verified lesson');
} finally {rmSync(root,{recursive:true,force:true});}
